### ISSUE TITLE
Scheduled Operations: Post a digest of unanswered StackExchange questions to Matrix

### ISSUE THREAD

**Issue by cmichi** [paritytech/matrix-admin-bot#21]
### Describe your problem and idea for the tool
> What you would like us to build? Which problem does it solve? What are the most important features this tool should have?

I would like to have a bot that posts _unanswered_ Substrate StackExchange questions for specified tags to our core team channel in Matrix.

* The questions should be posted as a digest to our core team channel.
* Each question should contain the number of unanswered days as an info.
* The digest should be posted every Monday 10 am CET.

This is the format I imagine:

* [What is the best way to make a cross contract call on ink!](https://substrate.stackexchange.com/questions/2797/what-is-the-best-way-to-make-a-cross-contract-call-on-ink) | 16 days unanswered
* [ink! How to Execute Function in a Specific Period of Time?](https://substrate.stackexchange.com/questions/3114/ink-how-to-execute-function-in-a-specific-period-of-time) | 2 days unanswered
* …

Please just keep the number of days and don't shorten it to weeks. Please sort by longest unanswered on the top.

Those are the tags that should be watched: `ink`, `smart-contract`, `pallet-contracts`, `substrate-contracts-node`, `cargo-contract`, `contracts`.

The digest should be posted to https://matrix.to/#/!nqwrcufvSwqTNsLMkj:matrix.parity.io?via=matrix.parity.io&via=web3.foundation.

Talk to me (Matrix: @michi:matrix.parity.io) or @athei (Matrix: @alext:matrix.parity.io) if you need an admin to set up the bot in the channel.

### How do you solve this problem now?
> What workarounds have you already tried? Do you have any docs describing these processes? Have you tried any opensource tools or found articles that could theoretically help us with that?

There is no solution yet and asking people to go through unanswered questions by themselves hasn't been fruitful.

### Importance and impact

- [ ] Low. Would be nice to have it at some point in the future
- [x] Medium. Lack of this instrument really prevents some people from working effectively
- [ ] High. If we don't make it by the deadline — we're doomed!

### Deadline
> Date, month or event reference to understand urgency.

31 June

### Additional info
> Any additional comments, links, inputs on what we need to know to understand your problem. You can mention other people here, so they can write their own inputs in comments. Remove this section if it's empty.

**Comment by mordamax** [comment]
@lovelaced they have an API. I'm thinking we could use github workflow cron job (similar to https://github.com/paritytech/opstooling/blob/master/.github/workflows/good-morning-techops.yml, simple python script)

@cmichi few questions:
1. How many questions (links) maximum should be posted per digest? 
2. stackexchange api requires to specify the exact [site](https://api.stackexchange.com/2.3/sites) the questions will be loaded from. Default is stackoverflow - is it ok, or need to be other site?
3. stackexchange has api for [unanswered](https://api.stackexchange.com/docs/unanswered-questions) and [no-answer-questions](https://api.stackexchange.com/docs/no-answer-questions). Difference is that `unanswered` might have an answer, but it's there's no "accepted". Which type of "unanswered" you'd want to see in digest?
4. Re. tags:
> From API description: To constrain questions returned to those with a set of tags, use the tagged parameter with a semi-colon delimited list of tags. This is an and constraint, passing tagged=c;java will return only those questions with both tags. As such, passing more than 5 tags will always return zero results.

I suppose that we will need to load unanswered questions by each tag separately, because combining the tags might exclude many questions where only one of the tags presented. This leads to the first question - how many questions overall do we need to post, and how many of those do we need to pull from each tag separately.

**Comment by mordamax** [comment]
so basically it will be like: 

- load all `ink` questions, sort by date, limit 15
- load all `smart-contract`, sort by date, limit 15
- load all `pallet-contracts`, sort by date, limit 15
etc ...
-> then sum up all these results, sort again by date, limit 15,
-> send to chat
